### ISSUE TITLE
Other Projects | Gallery - Inconsistent arrow links

### ISSUE THREAD

**Issue by erissek** [FatConan/jerzewska#19]
Inconsistent arrow links with the case studies and other projects

![image](https://user-images.githubusercontent.com/17589992/75121578-45d22980-568d-11ea-8fd5-dc7d0e76cc72.png)

**Comment by FatConan** [comment]
I think these are now consistent with expectations.
![image](https://user-images.githubusercontent.com/396596/75626536-29b81600-5bc0-11ea-9dfe-53f4cf6f3acb.png)
