### ISSUE TITLE
Link hover animation

### ISSUE THREAD

**Issue by erissek** [FatConan/jerzewska#9]
Nav, etc:
https://cssanimation.rocks/animating-links/ - animated underline effect like here

![image](https://user-images.githubusercontent.com/17589992/75115413-40a5b800-5656-11ea-8eb4-3a1652bbec61.png)

https://codepen.io/mxttsco/pen/KgodYm - left to right

**Comment by FatConan** [comment]
Navigation links updated, if this sort of underlining needs to be applied elsewhere it needs to be highlighted.
